### PR TITLE
Fix `advance_time_average!` logic by splitting init, zeroing, and collecting

### PR DESCRIPTION
**Pull request by hdrake**
Contributes to https://github.com/CliMA/Oceananigans.jl/pull/3717

### CODE REVIEW

**Comment by hdrake** [comment]
Here is the MWE example that I am using (slightly modified from @liuchihl's):

```julia
# this is a MWE for reproducing AveragedTimeInterval errors
using Oceananigans

function test_simulation(stop_time, Δt, δt, overwrite; τ=2)
    grid = RectilinearGrid(size=(2), z = (-1,1), topology=(Oceananigans.Flat, Oceananigans.Flat, Oceananigans.Bounded))
    uᵢ(z) = 0
    u_forcing(z, t) = sin(2*pi*t/τ)/2*(2*pi/τ)

    model = NonhydrostaticModel(; grid, 
                                  forcing = (u = u_forcing,),
                                  timestepper = :RungeKutta3)

   
    set!(model, u=uᵢ)

    simulation = Simulation(model; Δt, stop_time)
    u = model.velocities.u

    simulation.output_writers[:timeavg] = NetCDFOutputWriter(model, (u=u,),
                                        filename = "timeavg.nc",
                                        schedule = AveragedTimeInterval(1δt, window=δt, stride = 1),
                                        # schedule = TimeInterval(δt),
                                        overwrite_existing = overwrite)
                                 
    checkpointer = Checkpointer(model,
                                schedule = TimeInterval(stop_time),
                                prefix = "test",
                                cleanup = true)

    simulation.output_writers[:checkpointer] = checkpointer


function progress_message(sim) 
    wta = sim.output_writers[:timeavg].outputs["u"]
    wd = wta.window_start_time
    ws = wta.window_start_iteration
    pc = wta.previous_collection_time
    fo = wta.fetch_operand
    res = sum(wta.result)
    mct = model.clock.time
    interval = wta.schedule.interval
    window = wta.schedule.window
    cll = wta.schedule.collecting
    nat = next_actuation_time(wta.schedule)
    fat = wta.schedule.first_actuation_time
    actuation =  wta.schedule.actuations
    @info string("Iter: ", iteration(sim), ", time: ", prettytime(sim), ", model clock time:", mct, ", collecting: ", cll, ", u-avg: ", res, ", window_start_time: ", wd, ", window_start_iteration: ", ws, ", previous_collection_time:", pc, ", fetch_operand: ", fo, ", next_actuation_time: ", nat, ", first_actuation_time: ", fat, ", actuation: ", actuation)

    # @info string("Iter: ", iteration(sim), ", time: ", prettytime(sim), ", model clock time:", mct,
    #  ", window: ", window, ", u-avg: ", res, ", window_start_time: ", wd, ", window_start_iteration: ", ws, ", previous_collection_time:", pc, ", fetch_operand: ", fo, ", interval: ", interval, ", collecting: ", cll)
end
# progress_message(sim) = @info string("Iter: ", iteration(sim), ", time: ", prettytime(sim))
    simulation.callbacks[:progress] = Callback(progress_message, TimeInterval(δt))

    return simulation
end

function next_actuation_time(sch::AveragedTimeInterval)
    t₀ = sch.first_actuation_time
    N = sch.actuations
    T = sch.interval
    return t₀ + (N + 1) * T
end

if isfile("timeavg.nc")
    rm("timeavg.nc")
    println("File 'timeavg.nc' was successfully removed.")
else
    println("File 'timeavg.nc' does not exist.")
end

run(`sh -c "rm test_iteration*.jld2"`)

Δt = 0.001    # timestep (s)
T1 = 2.      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)

δt = 1.  # progress message interval and output saving interval
# Run a simulation that saves data to a checkpoint

simulation = test_simulation(T1, Δt, δt, true)
run!(simulation)

# Now try again, but picking up from the previous checkpoint
N = iteration(simulation)
checkpoint = "test_iteration$N.jld2"
simulation = test_simulation(T2, Δt, δt, false)
run!(simulation, pickup=checkpoint)

using NCDatasets
using CairoMakie
 
file = "timeavg.nc"
ds = Dataset(file)
t = ds["time"][:]
z = ds["zC"][:]
u = dropdims(ds["u"][:,:,:,:],dims = (1,2))
ln = lines(t[:],u[end,:])
close(ds)
ln

```

**Comment by liuchihl** [comment]
Thanks for the MWE

**Comment by hdrake** [comment]
The expected easy cases seem to work as intended:

1) When stop time = checkpoint time = multiple of output interval (= averaging window) = multiple of timestep
```julia
Δt = 0.001    # timestep (s)
T1 = 2.      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = 0.01  # progress message interval and output saving interval
```
Screenshot 2024-08-18 at 11 06 58 AM

2) The windowed averaging still works if the stop time, checkpointing, and averaging interval are not integer multiples of the timestep.
```julia
Δt = 0.0017    # timestep (s)
T1 = 2.      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = 0.01  # progress message interval and output saving interval
```

Screenshot 2024-08-18 at 11 09 59 AM

**Comment by liuchihl** [comment]
This looks very good!

**Comment by hdrake** [comment]
However, there seems to be a problem with longer-term averages right now, possibly related to checkpointing.

1) The results look pretty good when the averaging interval is equal to the run time:

```julia
Δt = 0.01    # timestep (s)
T1 = 2.      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = T1  # progress message interval and output saving interval
```

Screenshot 2024-08-18 at 11 13 20 AM

2) However, there seem to be some errors creeping in even with other easy cases like when 

```julia
Δt = 0.01    # timestep (s)
T1 = 2.      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = T1/2  # progress message interval and output saving interval
```

Because of the symmetry of the `cos` function, each of these time averages should be exactly equal, but they're not.

Screenshot 2024-08-18 at 11 15 56 AM

**Comment by hdrake** [comment]
Here is a more dramatic example:
```julia
Δt = 0.1    # timestep (s)
T1 = 2.      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = T1/2  # progress message interval and output saving interval
```

Screenshot 2024-08-18 at 11 33 07 AM

The more I think about this, the more I think this is actually not a bug but a feature how left Riemann sums non-symmetrically alias periodic signals at low temporal resolution. Indeed, this behavior vanishes at high temporal resolution:

```julia
Δt = 0.001    # timestep (s)
T1 = 2.      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = T1/2  # progress message interval and output saving interval
```

Screenshot 2024-08-18 at 11 39 10 AM

**Comment by liuchihl** [comment]
yeah, I think there is nothing wrong with the code. It is just that the time resolution should be high enough.

**Comment by liuchihl** [comment]
And the window size should not be too large. I wonder if there is a cut-off ratio of end time / window interval, where the aliasing issue won't creep in too much to contaminate the result.

**Comment by hdrake** [comment]
The one remaining problem with the current implementation, which is not improved by higher temporal resolution, is the fact that we are not storing the intermediate states of the accumulated `WindowedTimeAverage.result` in the checkpoints. Of course this doesn't matter if the checkpoint interval is an integer multiple of the `AveragedTimeInterval`, but it can be extremely wrong if the checkpoint cuts half-way through the averaging window.

For example, with
```julia
Δt = 0.001    # timestep (s)
T1 = 2.5      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = 1  # progress message interval and output saving interval
```
the first two windowed averages are correct but all of the ones after the checkpoint are incorrect because the `WindowedTimeAverage` fields are not saved in the checkpointer and are thus all initialized with zeros, setting the entire scheduler out of phase.

Screenshot 2024-08-18 at 11 43 38 AM

A temporary solution would be to trigger an error message if the `AveragedTimeInterval` is not an divisor of the checkpointing interval.

**Comment by hdrake** [comment]
> And the window size should not be too large.

I don't understand why you say this, @liuchihl? What is the problem with a large window size?

**Comment by liuchihl** [comment]
I was referring to when increasing δt the issue you mentioned emerges.

**Comment by hdrake** [comment]
> I was referring to when increasing δt the issue you mentioned emerges.

[This](https://github.com/liuchihl/Oceananigans.jl/pull/1#issuecomment-2295352912) issue doesn't have to do with increasing `δt`, it has to do with increasing the timestep `Δt` so that periodic oscillations in the solution are not adequately resolved.

The [separate checkpoint-aliasing issue](https://github.com/liuchihl/Oceananigans.jl/pull/1#issuecomment-2295354459) doesn't have to do with how big `δt` is, just whether it is a divisor of the checkpointing interval.

**Comment by liuchihl** [comment]
> ```julia
> Δt = 0.001    # timestep (s)
> T1 = 2.5      # first simulation stop time (s)
> T2 = 2T1    # second simulation stop time (s)
> δt = T1/2 
> ```

So I have tested the same parameters just like you did
image
The result makes sense to me somehow, even after checkpoint. The blue dots don't seem to be wrong. Though the fourth dot is higher than the rest, that's from the fact that the averaging window happens to include the entire crest. 
(Note that the yellow curve is a scatter plot with all timesteps included)
I am not sure why I haven't seen the aliasing issue you were referring to.

**Comment by hdrake** [comment]
> ```julia
> δt = T1/2 
> ```

Sorry, this was a typo. That case is fine because the averaging interval is a divisor of the checkpointing.

The problematic figure corresponds to:

> ```julia
> δt = 1.0
> ```

**Comment by liuchihl** [comment]
I realize not just `AveragedTimeInterval` has the issue when checkpoint is not a multiple of the window interval. If checkpoint is not a multiple of the output interval of `TimeInterval`, there is an out-of-phase issue. For example, when `schedule = TimeInterval(1.0)` along with 
```julia
Δt = 0.005    # timestep (s)
T1 = 2.5      # first simulation stop time (s)
T2 = 2T1    # second simulation stop time (s)
δt = 1 
```
I get: 
image
where the dashed line is from TimeInterval and dots are from averaged values.

So I think some change need to be done in the checkpoint file. Not sure if this will be a simple fix though.

**Comment by hdrake** [comment]
Yikes, this seems like a huge problem. I am guessing there are many users analyzing `TimeInterval` diagnostics that are not perfectly lined up with their checkpoints.

@glwagner, any advice as to how to checkpoint the scheduling information? For `TimeInterval` we at least need the `actuations` and other integer / floating point variables that track the output writer's progress. For `AverageTimeInterval` we'll also need to save the accumulated averages in `WindowedTimeAverage.result`.

**Comment by glwagner** [comment]
for checkpointing we need to refactor how output writers work. It's not a huge lift but will require a bit of design.

Is it feasible to first settle on a good design for `AverageTimeInterval` and then to work on checkpointing after that in a separate piece of work?

**Comment by hdrake** [comment]
> Is it feasible to first settle on a good design for `AverageTimeInterval` and then to work on checkpointing after that in a separate piece of work?

Yes, I think it is a good idea to split up those efforts / PRs. However, I would argue we should add warnings to this first PR letting people know that they should be cautious about the behavior of output writers when `checkpointing_interval % diagnostic_interval != 0` (probably we need a more robust check that this to account for rounding errors).

**Comment by glwagner** [comment]
> > Is it feasible to first settle on a good design for `AverageTimeInterval` and then to work on checkpointing after that in a separate piece of work?
> 
> Yes, I think it is a good idea to split up those efforts / PRs. However, I would argue we should add warnings to this first PR letting people know that they should be cautious about the behavior of output writers when `checkpointing_interval % diagnostic_interval != 0` (probably we need a more robust check that this to account for rounding errors).

The checkpointer basically needs to be redesigned or significantly extended to take into account the fact that we have to restore callbacks and schedules (not just the model state). Basically everything that has an evolving state has to be restored when restarting from a checkpoint.

I think it's actually going to be quite difficult to support general checkpointing for arbitrary callbacks, but maybe we can come up with a nice interface that will allow users to opt-in to such a thing. The schedule issue should be easier since we own that code.

**Pull request merged**
